parameters:
    database_dsn: '%database_driver%:host=%database_host%;dbname=%database_name%_test;charset=UTF8'

framework:
    test: true
    profiler:
        only_exceptions: false
    session:
        storage_id: 'session.storage.mock_file'
        handler_id: 'session.handler.native_file'
    router:
        resource: '%kernel.root_dir%/config/routing_test.yml'

assetic:
    debug:          false
    use_controller: true
    filters:
        less:
            node: '/usr/local/bin/node'
            node_paths:
                - '/usr/local/lib/node'
                - '/usr/local/lib/node_modules'

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    disable_delivery: true
