parameters:
    secret: 'v7ZtQR399vMmcAj9scjfKuvujesPeAZ4TSc5yxRtnf8AVKVmQ44TWtA6Tmy3NYHQ'
    locale: 'de_DE'

    log_level: 100

    app_version: '7d82j3ah2'

    database_driver: 'mysql'
    database_port: 3306
    database_host: ''
    database_name: ''
    database_user: ''
    database_password:
    database_dsn: '%database_driver%:host=%database_host%;dbname=%database_name%_%kernel.environment%;charset=UTF8'

    mailer_transport: 'smtp'
    mailer_host: '127.0.0.1'
    mailer_user:
    mailer_password:
    mailer_from_email:
    mailer_from_name:
    mailer_reply_to_email:
    mailer_encryption:
    mailer_port: 25
    mailer_auth_mode: 'plain'
    mailer_delivery_address:
