security:
    access_decision_manager:
        # strategy: Only grant access if *ALL* voters grant access.
        strategy: 'unanimous'

    encoders:
        Symfony\Component\Security\Core\User\User: 'plaintext'

    role_hierarchy:
        ROLE_ADMIN:
            - 'ROLE_USER'

        ROLE_SUPER_ADMIN:
            - 'ROLE_ADMIN'
            - 'ROLE_ALLOWED_TO_SWITCH'

    providers:
        in_memory:
            memory:
                users:
                    user: { password: 'userpass', roles: [ 'ROLE_USER' ] }
                    admin: { password: 'adminpass', roles: [ 'ROLE_ADMIN' ] }

    firewalls:
        dev:
            pattern:  '^/(_(profiler|wdt)|css|images|js)/'
            security: false

        main:
            pattern: ^/
            form_login:
                username_parameter: 'login[email]'
                password_parameter: 'login[password]'
                csrf_parameter:     'login[_token]'
                csrf_provider:      'form.csrf_provider'

                use_referer:  true
                default_target_path: '/'

            remember_me:
                key: 'ht2bTKL2qMJpMMmESmUKPVVXxtQbxd35WNq6DJc48yxJzsAa'
                remember_me_parameter: 'login[remember_me]'

            logout:
                path: '/logout'
                target: '/'

            anonymous:    true
            switch_user:  true

    access_control:
        -
            path: '^/_internal'
            ip: '127.0.0.1'
