services:
    controller.abstract:
        class: 'Controller\AbstractController'
        abstract: true
        calls:
            - [ 'setContainer', [ '@service_container' ] ]

    controller.registration:
        class: 'Controller\RegistrationController'
        parent: 'controller.abstract'

    controller.security:
        class: 'Controller\SecurityController'
        parent: 'controller.abstract'

    controller.welcome:
        class: 'Controller\WelcomeController'
        parent: 'controller.abstract'
