services:
    connection.pdo:
        class: PDO
        arguments:
            - '%database_dsn%'
            - '%database_user%'
            - '%database_password%'

    security.user_provider.propel:
        class: Security\PropelUserProvider
